// The CONTRACT-DRIFT GATE, and the package's own hygiene.
//
// `src/generated/schema.ts` is checked in so that consumers and CI need no
// codegen step. A checked-in generated file is only trustworthy if something
// fails when it stops matching its source — otherwise the types quietly become
// documentation of a contract that used to exist.
//
// This test regenerates from `api/openapi.yaml` IN PROCESS, with the same
// `openapi-typescript` version the package pins, and compares.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";
import { describe, expect, it } from "vitest";

import { CONTRACT_PATH, REPO_ROOT } from "./fixtures/index.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(HERE, "..");
const GENERATED = join(PACKAGE_ROOT, "src", "generated", "schema.ts");

interface PackageJson {
  private?: boolean;
  type?: string;
  main?: string;
  types?: string;
  engines?: { node?: string };
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  exports?: Record<string, Record<string, string>>;
  files?: string[];
}

const pkg = JSON.parse(readFileSync(join(PACKAGE_ROOT, "package.json"), "utf8")) as PackageJson;

describe("the checked-in types match the contract", () => {
  it("regenerating from api/openapi.yaml reproduces src/generated/schema.ts byte for byte", async () => {
    const ast = await openapiTS(new URL(`file://${CONTRACT_PATH.replace(/\\/g, "/")}`));
    const regenerated = astToString(ast);
    const committed = readFileSync(GENERATED, "utf8");
    expect(normalize(committed)).toBe(normalize(regenerated));
  }, 60_000);

  it("the contract lives where the client thinks it does", () => {
    expect(readFileSync(CONTRACT_PATH, "utf8")).toContain("THIS FILE IS THE CONTRACT.");
    expect(REPO_ROOT.replace(/\\/g, "/")).toMatch(/Solvent$/);
  });
});

describe("package hygiene", () => {
  it("has ZERO runtime dependencies", () => {
    // The claim in the README is enforced here rather than asserted there. An
    // EventSource polyfill is a HOOK, not a dependency: `fetchEventSource` is in
    // this package and uses nothing but the platform.
    expect(pkg.dependencies ?? {}).toEqual({});
  });

  it("pins every dev dependency to an EXACT version — no floating ^ on the codegen", () => {
    const dev = pkg.devDependencies ?? {};
    expect(Object.keys(dev).length).toBeGreaterThan(0);
    for (const [name, range] of Object.entries(dev)) {
      expect(range, `${name} must be pinned exactly, got ${range}`).toMatch(/^\d+\.\d+\.\d+$/);
    }
    // The generator in particular: a floating range would mean the checked-in
    // types could be regenerated differently on another machine, and the drift
    // test above would start failing for a reason nobody changed.
    expect(dev["openapi-typescript"]).toBe("7.13.0");
  });

  it("is PRIVATE until P5 — this package is built and proven, not published", () => {
    expect(pkg.private).toBe(true);
  });

  it("declares an ESM exports map with types, and Node >= 20", () => {
    expect(pkg.type).toBe("module");
    expect(pkg.engines?.node).toBe(">=20");
    expect(pkg.exports?.["."]).toEqual({
      types: "./dist/index.d.ts",
      import: "./dist/index.js",
    });
    expect(pkg.main).toBe("./dist/index.js");
    expect(pkg.types).toBe("./dist/index.d.ts");
    expect(pkg.files).toContain("dist");
  });
});

/**
 * Normalize away the two things that are not contract content: line endings (a
 * git checkout may rewrite them) and the CLI's "auto-generated" banner, which
 * `astToString` does not emit. Everything else is compared byte for byte.
 */
function normalize(source: string): string {
  return source
    .replace(/\r\n/g, "\n")
    .replace(/^\/\*\*\n \* This file was auto-generated by openapi-typescript\.\n \* Do not make direct changes to the file\.\n \*\/\n+/, "")
    .trimEnd();
}
