// Typed loader for the Book (W1) mock-route fixtures.
//
// The .json files are GENERATED by `tests/fixtures/generate-book.mjs` — see
// its provenance record: byte-identical copies of the contract-validated
// client fixtures, verbatim `api/openapi.yaml` examples, composed pages of
// canonical rows, and ONE documented derived negative (the monotonicity
// violation). Nothing here is hand-shaped wire data; this module only reads
// the committed bytes and names their types.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];

const here = path.dirname(fileURLToPath(import.meta.url));

function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

/** /v1/book — both engines served (client fixture, contract-validated). */
export const BOOK: Schemas["BookResponse"] = load("book.json");

/** /v1/book — aave withheld whole-engine: null bad debt with a named reason. */
export const BOOK_ENGINE_REFUSED: Schemas["BookResponse"] = load("book-engine-refused.json");

/** /v1/book — derived negative: a REAL monotonicity violation, named. */
export const BOOK_MONOTONICITY_VIOLATION: Schemas["BookResponse"] = load(
  "book-monotonicity-violation.json",
);

/** /v1/positions page 1 (aave) — the contract's own 200 example, verbatim. */
export const POSITIONS_AAVE_PAGE_1: Schemas["PositionsResponse"] = load(
  "positions-aave-page-1.json",
);

/** /v1/positions page 2 (aave) — the canonical REFUSED aave row, last page. */
export const POSITIONS_AAVE_PAGE_2: Schemas["PositionsResponse"] = load(
  "positions-aave-page-2.json",
);

/** /v1/positions page 1 (debt_manager) — liquidatable + refused canonical rows. */
export const POSITIONS_DM_PAGE_1: Schemas["PositionsResponse"] = load("positions-dm-page-1.json");

/** The 409 batch_superseded envelope — the contract's own example, verbatim. */
export const BATCH_SUPERSEDED: Schemas["BatchSupersededBody"] = load("batch-superseded.json");

/** The 503 no-servable-batch envelope (client fixture, contract-validated). */
export const BOOK_ERROR_UNAVAILABLE: Schemas["ErrorBody"] = load("book-error-unavailable.json");

/** The 400 bad-request envelope (client fixture, contract-validated). */
export const BOOK_ERROR_BAD_REQUEST: Schemas["ErrorBody"] = load("book-error-bad-request.json");
