// Typed loader for the Feed (W5) mock-route fixtures.
//
// The .json files are GENERATED by `tests/fixtures/generate-feed.mjs` — see
// its provenance record: the verbatim GET /v1/events contract example,
// composed pages derived from committed example rows by documented
// mechanical deltas, the OWED unit-tag cases (the closed set from
// internal/store/p5_events.go), ErrorBody envelopes, and the SSE snapshot
// payload around the /v1/positions example's batch. Nothing here is
// hand-shaped wire data; this module only reads the committed bytes and
// names their types.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];

/** The OWED C2 extension — mirrors lib/feed-data.ts's FeedChainEvent. */
type FeedEventsBody = Omit<Schemas["EventsResponse"], "events"> & {
  events: (Schemas["ChainEvent"] & { amount_unit?: string })[];
};

const here = path.dirname(fileURLToPath(import.meta.url));

function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

/** Cross-engine page 1 — the contract's own 200 example, verbatim. */
export const FEED_CROSS_PAGE_1: FeedEventsBody = load("feed-cross-page-1.json");

/** Cross-engine page 2 — the untimed tail continues (all rows untimed). */
export const FEED_CROSS_PAGE_2: FeedEventsBody = load("feed-cross-page-2.json");

/** Three timed rows: header times strictly DESC, heights NOT monotone. */
export const FEED_CROSS_TIMED: FeedEventsBody = load("feed-cross-timed.json");

/** Engine-scoped (aave) page: height order; one row's time is null. */
export const FEED_ENGINE_AAVE_PAGE_1: FeedEventsBody = load("feed-engine-aave-page-1.json");

/** The same walk under since_block 25,635,600 (params example's block). */
export const FEED_ENGINE_AAVE_SINCE: FeedEventsBody = load("feed-engine-aave-since.json");

/** types=["liquidation"] — the ledger page (null realized bonus case). */
export const FEED_LIQUIDATIONS: FeedEventsBody = load("feed-liquidations.json");

/** A well-formed filter that matches nothing. */
export const FEED_EMPTY: FeedEventsBody = load("feed-empty.json");

/** The OWED amount_unit cases — one row per member of the closed set. */
export const FEED_UNITS: FeedEventsBody = load("feed-units.json");

/** 400 — the store's own cursor-mode refusal text. */
export const FEED_ERROR_BAD_CURSOR: Schemas["ErrorBody"] = load("feed-error-bad-cursor.json");

/** 500 — a sanitized internal error envelope. */
export const FEED_ERROR_INTERNAL: Schemas["ErrorBody"] = load("feed-error-internal.json");

/** 429 — byte-identical client fixture (the lab wave's generator owns it). */
export const FEED_ERROR_RATE_LIMITED: Schemas["ErrorBody"] = load("error-rate-limited.json");

/** The SSE snapshot StreamPayload (batch = the /v1/positions example's). */
export const FEED_POSTURE_SNAPSHOT: Schemas["StreamPayload"] = load("feed-posture-snapshot.json");
