// Typed loader for the whole-book scenario-dashboard (W-SD-A) fixtures.
//
// The .json files are GENERATED by `tests/fixtures/generate-lab-book.mjs` —
// see its provenance record: the contract's own `/v1/scenarios` example
// envelope over definitions derived by the contract's OWN stated rule
// (`ScenarioDefinition` ≡ `Omit<Scenario, "results">`), the contract's run-book
// 200 example re-identified and given ONE internally consistent derived delta,
// and two documented single-field variants (a newer batch, a withheld engine).
// Nothing here is hand-shaped wire data; this module only reads the committed
// bytes and names their types.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];

const here = path.dirname(fileURLToPath(import.meta.url));

function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

/** `GET /v1/scenarios` — the committed listing, servable cold. */
export const SCENARIOS: Schemas["ScenariosResponse"] = load("scenarios.json");

/** `POST /v1/scenarios/eth_minus_30/run-book` @ batch 1 — a real nonzero delta. */
export const RUN_BOOK_ETH: Schemas["RunBookResponse"] = load("run-book.eth_minus_30.json");

/** The run-book example @ batch 2 — the supersession driver. */
export const RUN_BOOK_BATCH_2: Schemas["RunBookResponse"] = load("run-book.weeth.batch2.json");

/** The run-book example @ batch 1 with aave WITHHELD, refusal attached. */
export const RUN_BOOK_WITHHELD: Schemas["RunBookResponse"] = load("run-book.weeth-withheld.json");
