// Typed loader for the whole-book scenario-dashboard (W-SD-A) fixtures.
//
// The .json files are GENERATED by `tests/fixtures/generate-lab-book.mjs` —
// see its provenance record: the contract's own `/v1/scenarios` example
// envelope over definitions derived by the contract's OWN stated rule
// (`ScenarioDefinition` ≡ `Omit<Scenario, "results">`), the contract's run-book
// 200 example re-identified and given ONE internally consistent derived delta,
// and two documented single-field variants (a newer batch, a withheld engine).
// Nothing here is hand-shaped wire data; this module only reads the committed
// bytes and names their types.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];

const here = path.dirname(fileURLToPath(import.meta.url));

function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

/** `GET /v1/scenarios` — the committed listing, servable cold. */
export const SCENARIOS: Schemas["ScenariosResponse"] = load("scenarios.json");

/** `POST /v1/scenarios/eth_minus_30/run-book` @ batch 1 — a real nonzero delta. */
export const RUN_BOOK_ETH: Schemas["RunBookResponse"] = load("run-book.eth_minus_30.json");

/** The run-book example @ batch 2 — the supersession driver. */
export const RUN_BOOK_BATCH_2: Schemas["RunBookResponse"] = load("run-book.weeth.batch2.json");

/**
 * The SAME scenario's run-book @ batch 1 — what a re-run returns when the
 * daemon has pruned or receded (Wave R9). The row succeeds and comes back
 * pinned OLDER than the batch it was displaying.
 */
export const RUN_BOOK_WEETH_BATCH_1: Schemas["RunBookResponse"] = load(
  "run-book.weeth_market_depeg_oracles_held.json",
);

/** The run-book example @ batch 1 with aave WITHHELD, refusal attached. */
export const RUN_BOOK_WITHHELD: Schemas["RunBookResponse"] = load("run-book.weeth-withheld.json");

/**
 * THE 200 THAT NAMES NOBODY (Wave R11) — the run-book example with BOTH engine
 * arrays empty and the envelope otherwise untouched, batch and full-coverage
 * claim included.
 *
 * It typechecks as a healthy response because it IS one, by the contract's own
 * schemas: neither `engines` nor `excluded_engines` carries `minItems`, and no
 * cross-field rule ties either to the scenario's committed `engines[]`. Every
 * covered cell of the row it answers therefore reads UNANSWERED — which is why
 * nothing about the row's presentation may be inferred from the envelope.
 */
export const RUN_BOOK_NAMES_NOBODY: Schemas["RunBookResponse"] =
  load("run-book.names-nobody.json");

/**
 * THE 200 THAT CONTRADICTS ITSELF (Wave R12) — the withheld variant with
 * `engines[]` restored, so `aave_v3_etherfi` is named in BOTH arrays.
 *
 * It typechecks and parses as a healthy response for the same reason the
 * naming-nobody body does: neither array carries `uniqueItems`, no cross-field
 * rule ties the two together, and `lib/runbook.ts` validates nothing. Under the
 * pre-R12 cell precedence it rendered aave's numeric RESULT in the matrix while
 * the detail view rendered aave WITHHELD — one response, two answers, one cell.
 */
export const RUN_BOOK_CONTRADICTORY: Schemas["RunBookResponse"] =
  load("run-book.contradictory.json");

/** The same finding's other arm: `aave_v3_etherfi` appended to `engines[]` twice. */
export const RUN_BOOK_NAMED_TWICE: Schemas["RunBookResponse"] = load("run-book.named-twice.json");

/**
 * THE VERSION-SKEW PAIR (Wave R12, finding 2). Both are VALID responses; the
 * defect lives in the join between them.
 *
 * `SCENARIOS_V2` is the committed listing after a deployment re-cut
 * `ethfi_minus_50` — the set's `scenario_config_version` and the scenario's own
 * `version` both move to v2, and its `engines[]` narrows to aave alone.
 * `RUN_BOOK_ETHFI_V2` is what that deployment answers for the same id.
 *
 * Joined by scenario id ALONE against the RETAINED v1 listing (which covers
 * `debt_manager` for this id), the v2 book names none of v1's covered engines —
 * so R11 reads the row as ALL-HOLE and the header says the book named nobody,
 * while the response's real aave result sits in the detail view.
 */
export const SCENARIOS_V2: Schemas["ScenariosResponse"] = load("scenarios.v2.json");

/**
 * THE DELISTED ROW (Wave R13, finding 1) — the committed listing after a
 * deployment stopped publishing `weeth_market_depeg_oracles_held`.
 *
 * Every surviving definition is byte-identical to `SCENARIOS`, in wire order,
 * and `scenario_config_version` has NOT moved. That combination is what isolates
 * the finding: R12's identity guard and R11's coverage guard are both keyed per
 * row, so neither can say anything about a row the listing no longer carries —
 * `identity.get(id)` and `coverage.get(id)` are undefined, both checks correctly
 * decline to infer, and the run phase stored under that id sails past both into
 * the cohort as a DISPLAYED PIN with no rendered row anywhere on the table.
 */
export const SCENARIOS_REMOVED: Schemas["ScenariosResponse"] = load("scenarios.removed.json");

export const RUN_BOOK_ETHFI_V2: Schemas["RunBookResponse"] = load(
  "run-book.ethfi_minus_50.v2.json",
);

/**
 * THE RE-LISTED ROW (Wave R14, finding 1) — the committed listing after a
 * deployment republished `weeth_market_depeg_oracles_held` RE-CUT.
 *
 * It is `SCENARIOS` with exactly one field moved: that scenario's own `version`
 * is now v2. The set's `scenario_config_version` is held at v1 for the same
 * reason `SCENARIOS_REMOVED` holds it — moving it would refuse every surviving
 * row and hide the finding behind a guard that never sees it.
 *
 * The sequence it completes: v1 lists the row, `SCENARIOS_REMOVED` drops it (and
 * R13 correctly filters the orphaned phase out), and this listing brings the id
 * back attached to a DIFFERENT definition. `listedPhases` re-admits the stored
 * phase on the strength of the id alone; a `kind: "ok"` outcome defends itself
 * because the body publishes its own identity, but a RUNNING phase and a NON-OK
 * outcome publish nothing at all.
 */
export const SCENARIOS_RELISTED: Schemas["ScenariosResponse"] = load("scenarios.relisted.json");

/** What the republishing deployment answers for that id: the example at v2. */
export const RUN_BOOK_WEETH_V2: Schemas["RunBookResponse"] = load("run-book.weeth.v2.json");

/**
 * THE PARTIAL HOLE (Wave R14, finding 2) — `RUN_BOOK_WITHHELD` without the
 * refusal: aave dropped from `engines[]` and named in `excluded_engines[]`
 * NOWHERE.
 *
 * One of the row's two committed engines reached the run and the other is in
 * neither array, so aave's cell reads UNANSWERED while `excluded_engines` is
 * empty — which was the whole condition the detail panel rendered "excluded
 * engines: none — every engine's book reached the run" on.
 */
export const RUN_BOOK_PARTIAL_HOLE: Schemas["RunBookResponse"] = load(
  "run-book.partial-hole.json",
);
