// Typed loader for the Observatory (W4) mock-route fixtures.
//
// The .json files are GENERATED by `tests/fixtures/generate-observatory.mjs`
// — see its provenance record: the verbatim `api/openapi.yaml` 200 example
// (debt_manager, incl. the contract's own withheld bucket), ONE documented
// derived series (aave_v3_etherfi with a deliberately ABSENT 09:00 bucket),
// and the contract's ErrorBody envelope for the degraded rollup (code
// validated against the schema's enum; message = the store's typed refusal
// verbatim). Nothing here is hand-shaped wire data; this module only reads
// the committed bytes and names their types.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];

const here = path.dirname(fileURLToPath(import.meta.url));

function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

/**
 * /v1/observatory/series (debt_manager) — the contract's own 200 example,
 * verbatim: bucket 08:00 captured, bucket 09:00 WITHHELD (the newest bucket
 * is the refused one — the honest-render laws get exercised at rest).
 */
export const OBSERVATORY_SERIES_DM: Schemas["ObservatorySeriesResponse"] = load(
  "observatory-series-dm.json",
);

/**
 * /v1/observatory/series (aave_v3_etherfi) — the documented derived series:
 * four captured buckets with 09:00 deliberately ABSENT (no complete batch in
 * that bucket — the axis must show a named gap, never interpolate).
 */
export const OBSERVATORY_SERIES_AAVE: Schemas["ObservatorySeriesResponse"] = load(
  "observatory-series-aave.json",
);

/**
 * The degraded rollup envelope — `code: "unavailable"`, the statement a
 * deployment whose database predates migration 00016 serves.
 */
export const OBSERVATORY_DEGRADED: Schemas["ErrorBody"] = load("observatory-degraded.json");
