// Typed loader for the Proof Center (W6) mock-route fixtures.
//
// The .json files are GENERATED by `tests/fixtures/generate-proof.mjs` — see
// its provenance record: the verbatim GET /v1/evidence 200 example from
// api/openapi.yaml, plus THREE documented consistent deltas (the failed
// receipt, the missing receipt, the missing batch). Nothing here is
// hand-shaped wire data; this module only reads the committed bytes and
// names their types.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];

const here = path.dirname(fileURLToPath(import.meta.url));

function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

/** /v1/evidence — the contract's own 200 example, verbatim (pass receipt + serving batch). */
export const EVIDENCE_MANIFEST: Schemas["EvidenceResponse"] = load("evidence-manifest.json");

/** Derived negative: the receipt records a FAILED reconcile (fail · exit 1 · drift 3, real in the weld). */
export const EVIDENCE_PROOF_FAILED: Schemas["EvidenceResponse"] = load("evidence-proof-failed.json");

/** Derived negative: no committed receipt artifact — reconcile null, reason stated. */
export const EVIDENCE_NO_RECEIPT: Schemas["EvidenceResponse"] = load("evidence-no-receipt.json");

/** Derived negative: no servable batch — substrate null, reason from the NoBatch body. */
export const EVIDENCE_NO_BATCH: Schemas["EvidenceResponse"] = load("evidence-no-batch.json");
