// THE FRONTIER'S ONE GEOMETRY MODULE (LF-8 R2).
//
// The SVG places bar centres at `x(k)`. The LEDGER lays its columns out as
// `grid-template-columns: {marginLeft}px repeat(n, {slot}px)`. Both come from
// THIS function, called with the same arguments, so a ledger column and the
// bar it describes are aligned by construction rather than by two files
// agreeing to compute the same number the same way.
//
// R2 in the section template says it plainly: LEDGER geometry is generated by
// the same scale module as VISUAL — shared code, not shared intention.
//
// NO SUPPRESSION (LF-8). When the widest value in a column cannot fit the
// natural slot, the SLOT GROWS and the frame scrolls. The alternative — a
// ledger that drops or abbreviates values to fit — is a chart deciding which
// of the reader's numbers matter.
//
// Relative imports only: exercised by the unit specs under Playwright's
// transpiler as well as by Next.

/** LF-3: the y-tick gutter holds exact grouped money like `$2,000,000`. */
export const FRONTIER_MARGIN_LEFT = 88;

/** The right gutter: a half-slot of air so the last bar is not flush. */
export const FRONTIER_MARGIN_RIGHT = 16;

/** The pad a measured value column carries beside its glyphs (LF-8). */
export const FRONTIER_COLUMN_PAD = 16;

export interface FrontierScale {
  /** The shared left offset: the SVG's plot origin AND the ledger's gutter. */
  marginLeft: number;
  /** One grid sample's column width, in rendered px. */
  slot: number;
  /** The plot's own width: `slot × n`. */
  plotW: number;
  /** The full rendered width — may EXCEED the container, and then it scrolls. */
  width: number;
  /** True when `slot` is driven by the widest value rather than by the box. */
  valueDriven: boolean;
  /** The centre of grid sample `k`, in rendered px from the frame's origin. */
  x: (k: number) => number;
}

/**
 * @param measuredWidth the container's measured content width, in CSS px
 * @param n             the number of GRID samples (never the served count)
 * @param chPx          one mono `0` glyph's measured width, in CSS px
 * @param maxChars      the longest ledger value's length, in characters
 */
export function frontierScale(
  measuredWidth: number,
  n: number,
  chPx: number,
  maxChars: number,
): FrontierScale {
  const marginLeft = FRONTIER_MARGIN_LEFT;
  const available = Math.max(measuredWidth - marginLeft - FRONTIER_MARGIN_RIGHT, 1);
  const natural = n > 0 ? available / n : available;
  const longestValueWidth = maxChars * chPx + FRONTIER_COLUMN_PAD;
  const slot = Math.max(natural, longestValueWidth);
  const plotW = slot * n;
  return {
    marginLeft,
    slot,
    plotW,
    width: marginLeft + plotW + FRONTIER_MARGIN_RIGHT,
    valueDriven: longestValueWidth > natural,
    x: (k: number) => marginLeft + k * slot + slot / 2,
  };
}

/**
 * The y-domain ladder (LF-3): the smallest `[1,2,3,5,10] × 10^k` at or above
 * the series peak, computed in the ENGINE'S OWN INTEGER UNIT as bigint.
 *
 * Bars encode magnitude from zero, so the domain starts at zero and the top is
 * a round number a reader can divide in their head. A peak of `0n` yields a
 * top of `0n`: an axis whose maximum is invented above an all-zero series
 * would draw a ceiling nothing reaches.
 */
export function niceTop(peak: bigint): bigint {
  if (peak <= 0n) return 0n;
  const mantissas = [1n, 2n, 3n, 5n, 10n];
  let power = 1n;
  while (power * 10n <= peak) power *= 10n;
  for (const mantissa of mantissas) {
    const candidate = mantissa * power;
    if (candidate >= peak) return candidate;
  }
  return 10n * power;
}
