// THE FRONTIER'S ONE GEOMETRY MODULE, pinned (chart spec v4 LF-3 / LF-8).
//
// R2 in the section template: LEDGER geometry is generated by the same scale
// module as VISUAL — shared code, not shared intention. These pins are what
// make "the same" checkable: the SVG places bar centres at `x(k)` and the
// ledger lays out `grid-template-columns: {marginLeft}px repeat(n, {slot}px)`,
// so column k's centre IS `x(k)` by arithmetic rather than by two files
// agreeing to compute the same number the same way.
//
// Laws under test:
//   - NO SUPPRESSION at any width (LF-8): when the widest printed value does
//     not fit the natural slot, the SLOT GROWS and the frame scrolls. A ledger
//     that abbreviated to fit would be a chart deciding which of the reader's
//     numbers matter.
//   - the column count is the GRID's, never a constant. The served grid is
//     free to grow, and every consumer follows the data.
//   - the y-domain ladder is computed in the ENGINE'S OWN INTEGER UNIT as
//     bigint (LF-3): a domain top that went through a double is a rounded
//     number pretending to be a round one.

import { expect, test } from "@playwright/test";
import {
  FRONTIER_COLUMN_PAD,
  FRONTIER_MARGIN_LEFT,
  FRONTIER_MARGIN_RIGHT,
  frontierScale,
  niceTop,
} from "../../app/lab/frontierScale";

test("LF-3: the left gutter is 88px, wide enough for exact grouped money", () => {
  expect(FRONTIER_MARGIN_LEFT).toBe(88);
  expect(frontierScale(960, 6, 7, 8).marginLeft).toBe(88);
});

test("the natural slot fills the box exactly, and x(k) is that slot's centre", () => {
  const n = 6;
  const scale = frontierScale(960, n, 7, 4);
  const available = 960 - FRONTIER_MARGIN_LEFT - FRONTIER_MARGIN_RIGHT;
  expect(scale.slot).toBeCloseTo(available / n, 9);
  expect(scale.plotW).toBeCloseTo(available, 9);
  expect(scale.valueDriven).toBe(false);
  for (let k = 0; k < n; k += 1) {
    expect(scale.x(k)).toBeCloseTo(FRONTIER_MARGIN_LEFT + k * scale.slot + scale.slot / 2, 9);
  }
  // Adjacent centres are exactly one slot apart — the ledger's own step.
  expect(scale.x(1) - scale.x(0)).toBeCloseTo(scale.slot, 9);
});

// AC-40 in arithmetic form: the column count is the GRID's, and a longer grid
// simply produces more columns. Nothing here knows the number 6 or 7.
test("the grid length is the wire's — 6, 7 or 40 columns all lay out", () => {
  for (const n of [1, 5, 6, 7, 12, 40]) {
    const scale = frontierScale(960, n, 7, 4);
    expect(scale.plotW).toBeCloseTo(scale.slot * n, 9);
    expect(scale.x(n - 1)).toBeLessThanOrEqual(scale.width);
    expect(scale.x(0)).toBeGreaterThan(FRONTIER_MARGIN_LEFT);
  }
});

// AC-43 in arithmetic form.
test("LF-8 NO SUPPRESSION: a value wider than the box grows the slot and the frame", () => {
  const chPx = 7.2;
  // `$1,877,357.544497` is 17 characters at the Debt Manager's 6 decimals.
  const maxChars = 17;
  const measured = frontierScale(640, 7, chPx, maxChars);
  const longestValueWidth = maxChars * chPx + FRONTIER_COLUMN_PAD;
  expect(measured.valueDriven).toBe(true);
  expect(measured.slot).toBeCloseTo(longestValueWidth, 9);
  // The rendered width EXCEEDS the container: the frame scrolls rather than
  // the ledger dropping a value.
  expect(measured.width).toBeGreaterThan(640);
  // …and x(k) still lands on the same column centres, so the SVG and the
  // ledger stay aligned while they scroll together (AC-42).
  for (let k = 0; k < 7; k += 1) {
    expect(measured.x(k)).toBeCloseTo(
      FRONTIER_MARGIN_LEFT + k * measured.slot + measured.slot / 2,
      9,
    );
  }
});

test("`chPx` is a multiplier, not a rounding: a wider glyph widens the column", () => {
  const narrow = frontierScale(400, 7, 6, 17);
  const wide = frontierScale(400, 7, 8, 17);
  expect(wide.slot - narrow.slot).toBeCloseTo(17 * 2, 9);
});

test("a zero-column grid degrades without dividing by it", () => {
  const scale = frontierScale(960, 0, 7, 4);
  expect(Number.isFinite(scale.slot)).toBe(true);
  expect(scale.plotW).toBe(0);
});

// AC-42 across three viewport widths, in the arithmetic the DOM test measures.
test("column centres agree with x(k) at three widths", () => {
  for (const width of [640, 960, 1280]) {
    const scale = frontierScale(width, 7, 7.2, 6);
    for (let k = 0; k < 7; k += 1) {
      const ledgerCentre = scale.marginLeft + k * scale.slot + scale.slot / 2;
      expect(Math.abs(ledgerCentre - scale.x(k))).toBeLessThan(0.5);
    }
  }
});

test.describe("niceTop — the [1,2,3,5,10] × 10^k ladder in bigint (LF-3)", () => {
  test("the smallest rung at or above the peak", () => {
    expect(niceTop(1n)).toBe(1n);
    expect(niceTop(2n)).toBe(2n);
    expect(niceTop(4n)).toBe(5n);
    expect(niceTop(6n)).toBe(10n);
    expect(niceTop(11n)).toBe(20n);
    expect(niceTop(250n)).toBe(300n);
    expect(niceTop(4_200_000_000n)).toBe(5_000_000_000n);
    expect(niceTop(600_000_000_000n)).toBe(1_000_000_000_000n);
  });

  test("an exact rung is its own top — the peak never forces a rung above it", () => {
    expect(niceTop(300n)).toBe(300n);
    expect(niceTop(5_000_000_000n)).toBe(5_000_000_000n);
    expect(niceTop(10n ** 30n)).toBe(10n ** 30n);
  });

  test("a top is ALWAYS at or above the peak — no bar can exceed its own axis", () => {
    for (const peak of [1n, 7n, 99n, 101n, 3_162_277_660n, 999_999_999_999_999n]) {
      expect(niceTop(peak)).toBeGreaterThanOrEqual(peak);
    }
  });

  test("a zero peak yields a zero top: an invented ceiling nothing reaches is a lie", () => {
    expect(niceTop(0n)).toBe(0n);
    expect(niceTop(-5n)).toBe(0n);
  });

  test("30-digit peaks survive: the ladder never goes through a double", () => {
    const huge = 123_456_789_012_345_678_901_234_567_890n;
    expect(niceTop(huge)).toBe(2n * 10n ** 29n);
  });
});
