// web/tests/fixtures/demo/index.ts
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];
const here = path.dirname(fileURLToPath(import.meta.url));
function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

export const DEMO_BATCH_ID = 18251;
/** GENERATED by generate-demo.mjs — see its provenance header. */
export const DEMO_BOOK: Schemas["BookResponse"] = load("book.demo.json");
export const DEMO_POSITIONS_DM_PAGE_1: Schemas["PositionsResponse"] = load("positions-dm-demo-page-1.json");
export const DEMO_POSITIONS_DM_PAGE_2: Schemas["PositionsResponse"] = load("positions-dm-demo-page-2.json");
export const DEMO_META: Schemas["MetaResponse"] = load("meta.demo.json");
