// web/tests/fixtures/demo/index.ts
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { components } from "@solvent/client";

type Schemas = components["schemas"];
const here = path.dirname(fileURLToPath(import.meta.url));
function load<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(here, name), "utf8")) as T;
}

export const DEMO_BATCH_ID = 18251;
/** GENERATED by generate-demo.mjs — see its provenance header. */
export const DEMO_BOOK: Schemas["BookResponse"] = load("book.demo.json");
export const DEMO_POSITIONS_DM_PAGE_1: Schemas["PositionsResponse"] = load("positions-dm-demo-page-1.json");
export const DEMO_POSITIONS_DM_PAGE_2: Schemas["PositionsResponse"] = load("positions-dm-demo-page-2.json");
export const DEMO_META: Schemas["MetaResponse"] = load("meta.demo.json");

/** GENERATED by generate-demo-inspector.mjs — see its provenance header. The near account is the mockup's. */
export const DEMO_ADDRESS_NEAR: Schemas["AddressResponse"] = load("address-demo-near.json");
export const DEMO_ADDRESS_LIQUIDATABLE: Schemas["AddressResponse"] = load("address-demo-liquidatable.json");
export const DEMO_ADDRESS_HEALTHY: Schemas["AddressResponse"] = load("address-demo-healthy.json");
export const DEMO_ADDRESS_REFUSED: Schemas["AddressResponse"] = load("address-demo-refused.json");
export const DEMO_HISTORY_NEAR: Schemas["AddressHistoryResponse"] = load("history-demo-near.json");
export const DEMO_EVENTS_NEAR: Schemas["EventsResponse"] = load("events-demo-near.json");
export const DEMO_PARAMS_DM: Schemas["ParamsResponse"] = load("params-demo-dm.json");
export const DEMO_STRESS_NEAR: Schemas["StressResponse"] = load("stress-demo-near.json");
export const DEMO_NEAR_ADDR: string = DEMO_ADDRESS_NEAR.address;
export const DEMO_LIQUIDATABLE_ADDR: string = DEMO_ADDRESS_LIQUIDATABLE.address;
export const DEMO_HEALTHY_ADDR: string = DEMO_ADDRESS_HEALTHY.address;
export const DEMO_REFUSED_ADDR: string = DEMO_ADDRESS_REFUSED.address;

/** GENERATED by generate-demo-lab.mjs — see its provenance header. The run-book welds to the Book's eth_minus_30 waterfall. */
export const DEMO_SCENARIOS: Schemas["ScenariosResponse"] = load("scenarios-demo.json");
export const DEMO_RUN_BOOK_ETH: Schemas["RunBookResponse"] = load("run-book-demo-eth_minus_30.json");
export const DEMO_RUN_BOOK_SET: Schemas["RunBookSetResponse"] = load("run-book-set-demo.json");

/** GENERATED by generate-demo-secondary.mjs — see its provenance header. The newest bucket of each series IS the Book's engine card; the feed page is one cross-engine page under the Book's clock. */
export const DEMO_OBSERVATORY_DM: Schemas["ObservatorySeriesResponse"] = load("observatory-demo-dm.json");
export const DEMO_OBSERVATORY_AAVE: Schemas["ObservatorySeriesResponse"] = load("observatory-demo-aave.json");
export const DEMO_FEED_PAGE_1: Schemas["EventsResponse"] = load("events-demo-feed-page-1.json");
