// THE UI STATE MATRIX (plan AMENDMENT 1, item I — discharged by W7).
//
// One TABLE-DRIVEN spec driving EVERY surface through its state grid via
// mocked routes: loading → ok → each typed refusal/degraded state → error
// envelopes (429/500/503) → empty-but-proven states → live-posture states →
// responsive breakpoints. Each cell asserts the honest-UI laws that apply to
// it (spec §5):
//
//   - NULL never renders 0 ("the most dangerous zero");
//   - refused/withheld rows stay VISIBLE and COUNTED, never dropped;
//   - no fake freshness — every as-of is the wire's own statement;
//   - `found: null` NEVER renders "no position";
//   - live posture is never conflated with history;
//   - every chart states its as-of;
//   - severity is color AND form, never hue alone.
//
// EXTENDING: a new surface or state is ONE row in `MATRIX` — give it a
// surface, a state name, its mocked routes, an optional `act`, and the law
// assertions for that cell. The driver loop at the bottom does the rest.
//
// Fixtures: the landed per-surface fixtures are reused verbatim. The ONE
// derived fixture (a superseded-but-still-served positions envelope) is a
// documented single-field delta, provenance-commented at its definition.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test, type Page, type Route } from "@playwright/test";
import {
  DEMO_ADDRESS_NEAR,
  DEMO_EVENTS_NEAR,
  DEMO_HISTORY_NEAR,
  DEMO_META,
  DEMO_NEAR_ADDR,
  DEMO_PARAMS_DM,
  DEMO_RUN_BOOK_ETH,
  DEMO_SCENARIOS,
  DEMO_STRESS_NEAR,
} from "../fixtures/demo";
import {
  ADDRESS_FOUND,
  ADDRESS_NOT_FOUND,
  ADDRESS_UNKNOWABLE,
  EVENTS,
  FOUND_ADDR,
  HISTORY,
  NOT_FOUND_ADDR,
  PARAMS,
  UNKNOWABLE_ADDR,
} from "../fixtures/inspector";
import {
  FEED_CROSS_PAGE_1,
  FEED_EMPTY,
  FEED_ERROR_BAD_CURSOR,
  FEED_ERROR_INTERNAL,
  FEED_ERROR_RATE_LIMITED,
  FEED_POSTURE_SNAPSHOT,
} from "../fixtures/feed";
import { OBSERVATORY_DEGRADED, OBSERVATORY_SERIES_AAVE, OBSERVATORY_SERIES_DM } from "../fixtures/observatory";
import {
  EVIDENCE_MANIFEST,
  EVIDENCE_NO_BATCH,
  EVIDENCE_NO_RECEIPT,
  EVIDENCE_PROOF_FAILED,
} from "../fixtures/proof";

// ---------------------------------------------------------------------------
// Shared helpers.
// ---------------------------------------------------------------------------

const CORS = { "access-control-allow-origin": "*" };

function fulfillJson(route: Route, body: unknown, status = 200): Promise<void> {
  return route.fulfill({
    status,
    headers: CORS,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

/** A route that never answers — the honest way to hold a surface in `loading`. */
function stall(): Promise<void> {
  return new Promise<void>(() => undefined);
}

async function muteStream(page: Page): Promise<void> {
  await page.route("**/v1/stream**", (route) => route.abort());
}

/** SSE fulfilled with a fixed frame body (the transport reads it to EOF). */
async function mockStreamBody(page: Page, body: string): Promise<void> {
  await page.route("**/v1/stream**", (route) =>
    route.fulfill({
      status: 200,
      headers: { ...CORS, "content-type": "text/event-stream" },
      body,
    }),
  );
}

// Committed JSON fixtures, verbatim (generated by tests/fixtures/generate.mjs —
// nothing hand-shaped).
function labFixture(name: string): string {
  return readFileSync(fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url)), "utf8");
}

async function mockInspector(page: Page, address: unknown, history: unknown = HISTORY): Promise<void> {
  // The shell reads /v1/meta on every page (lib/meta.tsx); served here so no
  // Inspector cell leaves a request to whatever listens on :8080.
  await page.route("**/v1/meta*", (route) => fulfillJson(route, DEMO_META));
  await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_MANIFEST));
  await page.route("**/v1/params*", (route) => fulfillJson(route, PARAMS));
  await page.route("**/v1/events*", (route) => fulfillJson(route, EVENTS));
  await page.route("**/v1/address/*/history*", (route) => fulfillJson(route, history));
  // The Inspector's inline stress card reads the committed DM stress body.
  await page.route("**/v1/address/*/stress*", (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      headers: CORS,
      body: labFixture("stress-dm.json"),
    }),
  );
  // `*` never crosses `/`, so this does NOT swallow the /history or /stress routes above.
  await page.route("**/v1/address/*", (route) => fulfillJson(route, address));
}

async function mockObservatory(page: Page): Promise<void> {
  await page.route("**/v1/observatory/series*", (route) => {
    const engine = new URL(route.request().url()).searchParams.get("engine");
    return fulfillJson(
      route,
      engine === "debt_manager" ? OBSERVATORY_SERIES_DM : OBSERVATORY_SERIES_AAVE,
    );
  });
}

/** The run-book POST is cross-origin and preflighted; its OPTIONS leg is answered with these. */
const RUN_CORS = {
  ...CORS,
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "content-type, accept",
};

interface LabMocks {
  scenarios?: unknown;
  runBook?: unknown;
  runBookStatus?: number;
  address?: unknown;
  stress?: unknown;
  stressStatus?: number;
}

/**
 * Every route the Scenarios page can issue, by glob, from the demo dataset
 * (the shape of tests/e2e/lab.spec.ts's mockLab). One-address mode is the
 * Inspector's reading, so the Inspector's routes are served beside the listing.
 * `*` never crosses `/`, so the listing route does not swallow the run route.
 */
async function mockLab(page: Page, m: LabMocks = {}): Promise<void> {
  await page.route("**/v1/meta*", (route) => fulfillJson(route, DEMO_META));
  await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_MANIFEST));
  await page.route("**/v1/params*", (route) => fulfillJson(route, DEMO_PARAMS_DM));
  await page.route("**/v1/events*", (route) => fulfillJson(route, DEMO_EVENTS_NEAR));
  await page.route("**/v1/address/*/history*", (route) => fulfillJson(route, DEMO_HISTORY_NEAR));
  await page.route("**/v1/address/*/stress*", (route) =>
    fulfillJson(route, m.stress ?? DEMO_STRESS_NEAR, m.stressStatus ?? 200),
  );
  await page.route("**/v1/address/*", (route) => fulfillJson(route, m.address ?? DEMO_ADDRESS_NEAR));
  await page.route("**/v1/scenarios/*/run-book", (route) =>
    route.request().method() === "OPTIONS"
      ? route.fulfill({ status: 204, headers: RUN_CORS, body: "" })
      : route.fulfill({
          status: m.runBookStatus ?? 200,
          headers: RUN_CORS,
          contentType: "application/json",
          body: JSON.stringify(m.runBook ?? DEMO_RUN_BOOK_ETH),
        }),
  );
  await page.route("**/v1/scenarios", (route) => fulfillJson(route, m.scenarios ?? DEMO_SCENARIOS));
}

const SSE_SNAPSHOT_FRAME = `event: snapshot
data: ${JSON.stringify(FEED_POSTURE_SNAPSHOT)}

`;

/** No horizontal document overflow at a mobile breakpoint (±2px rounding). */
async function expectNoHorizontalOverflow(page: Page): Promise<void> {
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(2);
}

// ---------------------------------------------------------------------------
// The matrix. One row per (surface × state) cell.
// ---------------------------------------------------------------------------

interface Cell {
  surface: string;
  state: string;
  path: string;
  /** Mobile cells set a viewport BEFORE navigation. */
  viewport?: { width: number; height: number };
  mock: (page: Page) => Promise<void>;
  /** Optional interaction between navigation and verification. */
  act?: (page: Page) => Promise<void>;
  verify: (page: Page) => Promise<void>;
}

const MATRIX: Cell[] = [
  // ---- Inspector ------------------------------------------------------
  {
    surface: "inspector",
    state: "loading",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", stall);
      await page.route("**/v1/params*", stall);
      await page.route("**/v1/events*", stall);
      await page.route("**/v1/address/*/history*", stall);
      await page.route("**/v1/address/*/stress*", stall);
      await page.route("**/v1/address/*", stall);
    },
    verify: async (page) => {
      await expect(page.getByTestId("inspector-surface")).toHaveAttribute("data-state", "loading");
      await expect(page.getByTestId("inspector-verdict-headline")).toHaveText(
        "Looking up this address…",
      );
    },
  },
  {
    surface: "inspector",
    state: "ok:found-with-stale-price",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_FOUND);
    },
    verify: async (page) => {
      await expect(page.getByTestId("inspector-surface")).toHaveAttribute(
        "data-state",
        "liquidatable",
      );
      // No fake freshness: the stale verdict is the LEGACY card's own visible
      // state — it rides the Aave position, never the Cash verdict.
      await expect(page.getByTestId("inspector-legacy")).toContainText("stale price");
    },
  },
  {
    surface: "inspector",
    state: "empty:not-found-definitive",
    path: `/inspector/${NOT_FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_NOT_FOUND);
    },
    verify: async (page) => {
      // The ONE state entitled to say "no position": a definitive negative
      // from a complete lookup — empty, but PROVEN empty.
      await expect(page.getByTestId("inspector-surface")).toHaveAttribute(
        "data-state",
        "no-position",
      );
      await expect(page.getByTestId("inspector-verdict-headline")).toHaveText(
        "No Cash or Aave position in batch 1.",
      );
      await expect(page.locator("main")).not.toContainText("Cannot say");
    },
  },
  {
    surface: "inspector",
    state: "refused:found-null-unknowable",
    path: `/inspector/${UNKNOWABLE_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_UNKNOWABLE);
    },
    verify: async (page) => {
      // found:null NEVER renders "no position": the withheld book is NAMED
      // in the verdict, and the definitive-negative sentence is absent.
      await expect(page.getByTestId("inspector-surface")).toHaveAttribute(
        "data-state",
        "cannot-compute",
      );
      await expect(page.getByTestId("inspector-verdict-headline")).toHaveText(
        "Cannot say — the Cash book is withheld this batch.",
      );
      await expect(page.locator("main")).not.toContainText("No Cash or Aave position");
    },
  },
  {
    surface: "inspector",
    state: "ok:history-gaps-hoverable",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_FOUND);
    },
    verify: async (page) => {
      // The refused batch is a GAP (never a value): the legacy history card
      // renders, and the History card states the law in its own words.
      await expect(page.getByTestId("inspector-history-legacy")).toBeVisible();
      await expect(page.getByTestId("inspector-history")).toContainText("gaps drawn as gaps");
    },
  },
  {
    surface: "inspector",
    state: "error:429",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_MANIFEST));
      await page.route("**/v1/params*", (route) => fulfillJson(route, PARAMS));
      await page.route("**/v1/events*", (route) => fulfillJson(route, EVENTS));
      await page.route("**/v1/address/*/history*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
      await page.route("**/v1/address/*/stress*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
      await page.route("**/v1/address/*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
    },
    verify: async (page) => {
      // An error is NOT an answer: neither "no position" nor a position. The
      // dek carries the lookup error's own words, sentence-cased by the
      // headline module (lib/lookup-error.ts builds "rate limited (429)…").
      await expect(page.getByTestId("inspector-surface")).toHaveAttribute(
        "data-state",
        "unavailable",
      );
      await expect(page.getByTestId("inspector-verdict-dek")).toContainText("Rate limited (429)");
      await expect(page.getByTestId("inspector-verdict-dek")).toContainText(
        "an error is not an answer",
      );
    },
  },
  {
    surface: "inspector",
    state: "responsive:mobile",
    path: `/inspector/${FOUND_ADDR}`,
    viewport: { width: 390, height: 844 },
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_FOUND);
    },
    verify: async (page) => {
      await expect(page.getByTestId("inspector-surface")).toHaveAttribute(
        "data-state",
        /liquidatable|near|healthy/,
      );
      await expectNoHorizontalOverflow(page);
    },
  },

  // ---- Scenarios ------------------------------------------------------
  {
    surface: "lab",
    state: "ok",
    // One-address mode via the deep link: the Inspector's reading under the committed scenarios.
    path: `/lab?address=${DEMO_NEAR_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockLab(page);
    },
    verify: async (page) => {
      await expect(page.getByTestId("lab-surface")).toHaveAttribute("data-state", "rows");
      // Every scenario the wire evaluated for this address is a row; none is dropped.
      await expect(page.getByTestId("lab-address-table").locator("tbody tr")).toHaveCount(
        DEMO_STRESS_NEAR.scenarios.length,
      );
    },
  },
  {
    surface: "lab",
    state: "refused:found-null-unknowable",
    path: `/lab?address=${UNKNOWABLE_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      // The committed unknowable stress body, re-identified to the lookup's
      // address so the cell mocks one address end to end.
      const stress = JSON.parse(labFixture("stress-unknowable.json")) as { address: string };
      await mockLab(page, {
        address: ADDRESS_UNKNOWABLE,
        stress: { ...stress, address: UNKNOWABLE_ADDR },
      });
    },
    verify: async (page) => {
      // `found: null` is a cannot-say — never "no position".
      await expect(page.getByTestId("lab-surface")).toHaveAttribute("data-state", "withheld");
      await expect(page.getByTestId("lab-verdict-headline")).toContainText("Cannot say");
      await expect(page.locator("main")).not.toContainText("No Cash position");
    },
  },
  {
    surface: "lab",
    state: "error:429",
    path: `/lab?address=${DEMO_NEAR_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockLab(page, { stress: FEED_ERROR_RATE_LIMITED, stressStatus: 429 });
    },
    verify: async (page) => {
      // The scenarios could not be run; the position above is unaffected.
      await expect(page.getByTestId("lab-surface")).toHaveAttribute("data-state", "unavailable");
      await expect(page.getByTestId("lab-verdict-headline")).toHaveText(
        "The scenarios for 0x7a3f…c21e could not be run.",
      );
      await expect(page.getByTestId("lab-verdict-dek")).toContainText("(429)");
    },
  },
  {
    surface: "lab",
    state: "degraded:run-book-not-served-404",
    path: "/lab",
    mock: async (page) => {
      await muteStream(page);
      await mockLab(page, {
        runBook: JSON.parse(labFixture("error-not-found.json")) as unknown,
        runBookStatus: 404,
      });
    },
    // Book mode is the default and learns the committed set from
    // `GET /v1/scenarios`, so the 404 state is one click from arrival.
    act: async (page) => {
      await page.getByTestId("lab-run").click();
    },
    verify: async (page) => {
      // The honest 404: named state, no spinner, no fake data.
      await expect(page.getByTestId("lab-surface")).toHaveAttribute("data-state", "not-served");
      await expect(page.getByTestId("lab-verdict-headline")).toHaveText(
        "Book-wide stress is not served by this deployment.",
      );
      await expect(page.getByTestId("lab-heatmap")).toHaveCount(0);
    },
  },

  // ---- Observatory ----------------------------------------------------
  {
    surface: "observatory",
    state: "loading",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/observatory/series*", stall);
    },
    verify: async (page) => {
      await expect(page.getByTestId("history-surface")).toHaveAttribute("data-state", "loading");
      await expect(page.getByTestId("history-kpi-debt")).toHaveAttribute("aria-busy", "true");
    },
  },
  {
    surface: "observatory",
    state: "ok:absent-bucket",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await mockObservatory(page);
    },
    // The page opens on Cash; the contract's absent hour lives in the legacy engine's series.
    act: async (page) => {
      await page.getByTestId("history-engine-aave_v3_etherfi").click();
    },
    verify: async (page) => {
      // The record states its as-of (the newest bucket's own watermark)…
      await expect(page.getByTestId("history-point")).toContainText("watermark block");
      // …and an ABSENT bucket is a NAMED gap on the axis, never interpolated.
      // (toBeAttached: a stroke-only SVG tick has a zero-width box, which
      // Playwright's visibility heuristic reports as hidden.)
      await expect(
        page.getByTestId("history-chart").locator('[data-kind="absent"]').first(),
      ).toBeAttached();
    },
  },
  {
    surface: "observatory",
    state: "refused:withheld-bucket",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await mockObservatory(page);
    },
    act: async (page) => {
      await page.getByTestId("history-engine-debt_manager").click();
    },
    verify: async (page) => {
      // Severity = color AND form: the withheld gap wears the outlined
      // warn square, not just a hue; the newest bucket's tiles are dashed.
      await expect(page.getByTestId("obs-gap-warn").first()).toBeVisible();
      await expect(
        page.getByTestId("history-chart").locator('[data-kind="withheld"]').first(),
      ).toBeAttached();
      await expect(page.getByTestId("history-kpi-debt")).toHaveAttribute("data-tone", "refused");
      await expect(page.locator("body")).not.toContainText("$0");
    },
  },
  {
    surface: "observatory",
    state: "degraded:rollup-unavailable",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/observatory/series*", (route) =>
        fulfillJson(route, OBSERVATORY_DEGRADED, 503),
      );
    },
    verify: async (page) => {
      await expect(page.getByTestId("history-surface")).toHaveAttribute("data-state", "degraded");
      const verdict = page.getByTestId("history-verdict");
      await expect(verdict).toHaveAttribute("data-variant", "refused");
      // The route's one source of `unavailable` is a rollup that was never migrated: a fact about the deployment, in the refused register.
      await expect(verdict).toContainText("on this deployment yet.");
      // Never an empty chart, never zeros.
      await expect(page.getByTestId("history-chart")).toHaveCount(0);
      await expect(page.locator('[data-testid^="history-kpi-"]')).toHaveCount(0);
    },
  },
  {
    surface: "observatory",
    state: "error:500",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/observatory/series*", (route) =>
        fulfillJson(route, FEED_ERROR_INTERNAL, 500),
      );
    },
    verify: async (page) => {
      await expect(page.getByTestId("history-surface")).toHaveAttribute("data-state", "unavailable");
      await expect(page.getByTestId("history-verdict")).toContainText(
        "unavailable, and none of it is being shown as empty",
      );
    },
  },

  // ---- Feed -----------------------------------------------------------
  {
    surface: "feed",
    state: "ok:untimed-tail-disclosed",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_CROSS_PAGE_1));
    },
    verify: async (page) => {
      const rows = page.locator('[data-testid^="activity-row-"]');
      await expect(rows).toHaveCount(2);
      // No fake freshness: the untimed row renders its BLOCK, never an
      // invented timestamp, and the tail is DISCLOSED as the dim row.
      await expect(rows.nth(1)).toHaveClass(/dim/);
      await expect(rows.nth(1).locator("td").first()).toHaveText("block 154,796,490");
    },
  },
  {
    surface: "feed",
    state: "empty:filter-matches-nothing",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_EMPTY));
    },
    verify: async (page) => {
      const empty = page.getByTestId("activity-table");
      await expect(empty).toContainText("no recorded chain action matches this filter");
      await expect(empty).toContainText("a real answer");
      await expect(page.locator('[data-testid^="activity-row-"]')).toHaveCount(0);
    },
  },
  {
    surface: "feed",
    state: "refused:bad-cursor-400",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => {
        const url = new URL(route.request().url());
        if (url.searchParams.get("cursor") === null)
          return fulfillJson(route, FEED_CROSS_PAGE_1);
        return fulfillJson(route, FEED_ERROR_BAD_CURSOR, 400);
      });
    },
    act: async (page) => {
      await expect(page.locator('[data-testid^="activity-row-"]')).toHaveCount(2);
      await page.getByTestId("activity-load-more").click();
    },
    verify: async (page) => {
      // The refusal renders the envelope's own words; loaded rows survive.
      await expect(page.getByTestId("activity-refusal")).toBeVisible();
      await expect(page.getByTestId("activity-restart")).toBeVisible();
      await expect(page.locator('[data-testid^="activity-row-"]')).toHaveCount(2);
    },
  },
  {
    surface: "feed",
    state: "error:429",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
    },
    verify: async (page) => {
      await expect(page.getByTestId("activity-error")).toContainText("rate limit");
    },
  },
  {
    surface: "feed",
    state: "error:500",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_ERROR_INTERNAL, 500));
    },
    verify: async (page) => {
      await expect(page.getByTestId("activity-error")).toContainText("failed to build the response");
    },
  },
  {
    surface: "feed",
    state: "live:no-base-frame",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_CROSS_PAGE_1));
    },
    verify: async (page) => {
      // Nothing is pretended: no snapshot means no batch strip at all.
      await expect(page.getByTestId("activity-live-none")).toContainText("nothing live is shown");
      await expect(page.getByTestId("activity-live-batch")).toHaveCount(0);
    },
  },
  {
    surface: "feed",
    state: "live:snapshot-never-history",
    path: "/feed",
    mock: async (page) => {
      await mockStreamBody(page, SSE_SNAPSHOT_FRAME);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_CROSS_PAGE_1));
    },
    verify: async (page) => {
      // Live posture renders the batch's REAL watermark vector…
      await expect(page.getByTestId("activity-live-batch")).toContainText("Batch 1");
      await expect(page.getByTestId("activity-live-batch")).toContainText("at block 25,635,618");
      // …and stays labeled live-only: posture is never conflated with history.
      await expect(page.getByTestId("activity-live")).toContainText("this connection only");
    },
  },

  // ---- Verification ---------------------------------------------------
  {
    surface: "proof",
    state: "ok:proof-and-live-split",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_MANIFEST));
    },
    verify: async (page) => {
      // Two subjects; the reconciled-exact claim lives ONLY on the proof
      // card — a live batch never reads as reconciled-exact.
      await expect(page.getByTestId("verification-surface")).toHaveAttribute("data-receipt", "exact");
      await expect(page.getByTestId("verification-subject-proof")).toContainText("PROOF · EXACT");
      await expect(page.getByTestId("verification-subject-live")).not.toContainText("PROOF · EXACT");
    },
  },
  {
    surface: "proof",
    state: "refused:receipt-rejected",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_PROOF_FAILED));
    },
    verify: async (page) => {
      await expect(page.getByTestId("verification-surface")).toHaveAttribute("data-receipt", "failed");
      await expect(page.getByTestId("verification-proof-status")).toContainText("RECEIPT REJECTED");
      // The live subject keeps ITS truth — serving continues, unconflated.
      await expect(page.getByTestId("verification-live-status")).toContainText("SERVING");
      await expect(page.locator("body")).not.toContainText("PROOF · EXACT @");
    },
  },
  {
    surface: "proof",
    state: "empty:no-committed-receipt",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_NO_RECEIPT));
    },
    verify: async (page) => {
      await expect(page.getByTestId("verification-surface")).toHaveAttribute("data-receipt", "none");
      await expect(page.getByTestId("verification-proof-status")).toContainText("NO COMMITTED RECEIPT");
      await expect(page.getByTestId("verification-live-status")).toContainText("SERVING");
    },
  },
  {
    surface: "proof",
    state: "error:no-servable-batch",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_NO_BATCH));
    },
    verify: async (page) => {
      await expect(page.getByTestId("verification-live-status")).toContainText("NO SERVABLE BATCH");
      // No key is ever fabricated for a batch that does not exist.
      await expect(page.getByTestId("verification-key")).toContainText("never fabricated");
    },
  },
  {
    surface: "proof",
    state: "error:evidence-unreachable",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => route.abort());
    },
    verify: async (page) => {
      await expect(page.getByTestId("verification-surface")).toHaveAttribute("data-state", "unavailable");
      // Neither subject is invented while the manifest is unreachable.
      await expect(page.getByTestId("verification-subject-proof")).toHaveCount(0);
      await expect(page.getByTestId("verification-subject-live")).toHaveCount(0);
    },
  },

  // ---- Developers -----------------------------------------------------
  {
    surface: "developers",
    state: "ok",
    path: "/developers",
    mock: async (page) => {
      await muteStream(page);
    },
    verify: async (page) => {
      // Generated verbatim from the contract; the error vocabulary renders
      // including the 409 supersession envelope.
      await expect(page.getByTestId("api-endpoint-getEvidence")).toBeVisible();
      await expect(page.getByTestId("api-error-BatchSuperseded")).toBeVisible();
    },
  },
];

// ---------------------------------------------------------------------------
// The driver: one test per cell.
// ---------------------------------------------------------------------------

for (const cell of MATRIX) {
  test(`${cell.surface} × ${cell.state}`, async ({ page }) => {
    if (cell.viewport !== undefined) await page.setViewportSize(cell.viewport);
    await cell.mock(page);
    await page.goto(cell.path);
    if (cell.act !== undefined) await cell.act(page);
    await cell.verify(page);
  });
}
