// THE UI STATE MATRIX (plan AMENDMENT 1, item I — discharged by W7).
//
// One TABLE-DRIVEN spec driving EVERY surface through its state grid via
// mocked routes: loading → ok → each typed refusal/degraded state → error
// envelopes (429/500/503) → empty-but-proven states → live-posture states →
// responsive breakpoints. Each cell asserts the honest-UI laws that apply to
// it (spec §5):
//
//   - NULL never renders 0 ("the most dangerous zero");
//   - refused/withheld rows stay VISIBLE and COUNTED, never dropped;
//   - no fake freshness — every as-of is the wire's own statement;
//   - `found: null` NEVER renders "no position";
//   - live posture is never conflated with history;
//   - every chart states its as-of;
//   - severity is color AND form, never hue alone.
//
// EXTENDING: a new surface or state is ONE row in `MATRIX` — give it a
// surface, a state name, its mocked routes, an optional `act`, and the law
// assertions for that cell. The driver loop at the bottom does the rest.
//
// Fixtures: the landed per-surface fixtures are reused verbatim. The ONE
// derived fixture (a superseded-but-still-served positions envelope) is a
// documented single-field delta, provenance-commented at its definition.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test, type Page, type Route } from "@playwright/test";
import {
  BATCH_SUPERSEDED,
  BOOK,
  BOOK_ENGINE_REFUSED,
  BOOK_ERROR_UNAVAILABLE,
  POSITIONS_AAVE_PAGE_1,
  POSITIONS_AAVE_PAGE_2,
  POSITIONS_DM_PAGE_1,
} from "../fixtures/book";
import {
  ADDRESS_FOUND,
  ADDRESS_NOT_FOUND,
  ADDRESS_UNKNOWABLE,
  EVENTS,
  FOUND_ADDR,
  HISTORY,
  NOT_FOUND_ADDR,
  PARAMS,
  UNKNOWABLE_ADDR,
} from "../fixtures/inspector";
import {
  FEED_CROSS_PAGE_1,
  FEED_EMPTY,
  FEED_ERROR_BAD_CURSOR,
  FEED_ERROR_INTERNAL,
  FEED_ERROR_RATE_LIMITED,
  FEED_POSTURE_SNAPSHOT,
} from "../fixtures/feed";
import { OBSERVATORY_DEGRADED, OBSERVATORY_SERIES_AAVE, OBSERVATORY_SERIES_DM } from "../fixtures/observatory";
import {
  EVIDENCE_MANIFEST,
  EVIDENCE_NO_BATCH,
  EVIDENCE_NO_RECEIPT,
  EVIDENCE_PROOF_FAILED,
} from "../fixtures/proof";

// ---------------------------------------------------------------------------
// Shared helpers.
// ---------------------------------------------------------------------------

const CORS = { "access-control-allow-origin": "*" };
const API = "http://localhost:8080";

function fulfillJson(route: Route, body: unknown, status = 200): Promise<void> {
  return route.fulfill({
    status,
    headers: CORS,
    contentType: "application/json",
    body: JSON.stringify(body),
  });
}

/** A route that never answers — the honest way to hold a surface in `loading`. */
function stall(): Promise<void> {
  return new Promise<void>(() => undefined);
}

async function muteStream(page: Page): Promise<void> {
  await page.route("**/v1/stream**", (route) => route.abort());
}

/** SSE fulfilled with a fixed frame body (the transport reads it to EOF). */
async function mockStreamBody(page: Page, body: string): Promise<void> {
  await page.route("**/v1/stream**", (route) =>
    route.fulfill({
      status: 200,
      headers: { ...CORS, "content-type": "text/event-stream" },
      body,
    }),
  );
}

async function mockBookOk(page: Page): Promise<void> {
  await page.route("**/v1/book", (route) => fulfillJson(route, BOOK));
  // Cursor-aware: the W-UX-C sentinel walks short books to exhaustion on its
  // own, so the cursor page must terminate (PAGE_2 carries next_cursor null).
  await page.route("**/v1/positions*", (route) => {
    const url = new URL(route.request().url());
    if (url.searchParams.get("engine") === "debt_manager")
      return fulfillJson(route, POSITIONS_DM_PAGE_1);
    if (url.searchParams.get("cursor") === null)
      return fulfillJson(route, POSITIONS_AAVE_PAGE_1);
    return fulfillJson(route, POSITIONS_AAVE_PAGE_2);
  });
}

async function mockInspector(page: Page, address: unknown, history: unknown = HISTORY): Promise<void> {
  await page.route("**/v1/params*", (route) => fulfillJson(route, PARAMS));
  await page.route("**/v1/events*", (route) => fulfillJson(route, EVENTS));
  await page.route("**/v1/address/*/history*", (route) => fulfillJson(route, history));
  // `*` never crosses `/`, so this does NOT swallow the /history route above.
  await page.route("**/v1/address/*", (route) => fulfillJson(route, address));
}

async function mockObservatory(page: Page): Promise<void> {
  await page.route("**/v1/observatory/series*", (route) => {
    const engine = new URL(route.request().url()).searchParams.get("engine");
    return fulfillJson(
      route,
      engine === "debt_manager" ? OBSERVATORY_SERIES_DM : OBSERVATORY_SERIES_AAVE,
    );
  });
}

// Lab fixtures load exactly as the landed lab spec loads them (generated by
// tests/fixtures/generate.mjs — nothing hand-shaped).
function labFixture(name: string): string {
  return readFileSync(fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url)), "utf8");
}
const STRESS_AAVE = JSON.parse(labFixture("stress-aave.json")) as {
  address: string;
  scenarios: { id: string }[];
};
const STRESS_UNKNOWABLE = JSON.parse(labFixture("stress-unknowable.json")) as { address: string };

async function mockStress(page: Page, addr: string, body: string, status = 200): Promise<void> {
  await page.route(`${API}/v1/address/${addr}/stress`, (route) =>
    route.fulfill({ status, contentType: "application/json", headers: CORS, body }),
  );
}

/**
 * The two COLD routes book mode reads on arrival (W-SD-A). Mocked wherever the
 * Lab is visited so no state case depends on a live API.
 */
async function mockLabCold(page: Page): Promise<void> {
  await page.route(`${API}/v1/scenarios`, (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      headers: CORS,
      body: labFixture("scenarios.json"),
    }),
  );
  await page.route(`${API}/v1/book`, (route) =>
    route.fulfill({
      status: 200,
      contentType: "application/json",
      headers: CORS,
      body: labFixture("book.json"),
    }),
  );
}

/**
 * Fill + submit the Lab address form, hydration-safe (the landed lab pattern).
 *
 * W-SD-A CHANGED THIS HELPER: whole-book view is the default register, so
 * address mode is reached the way a reader reaches it — one click on the
 * secondary tab.
 */
async function runStress(page: Page, addr: string): Promise<void> {
  await page.getByTestId("mode-address").click();
  const input = page.getByTestId("lab-address-input");
  const button = page.getByTestId("run-stress-button");
  await expect(async () => {
    await input.fill(addr);
    await expect(button).toBeEnabled({ timeout: 250 });
  }).toPass();
  await button.click();
}

/**
 * DERIVED FIXTURE (provenance): a documented TWO-FIELD delta of the landed
 * `positions-aave-page-1.json` — the same envelope with
 * `batch.supersession.superseded = true`, and `next_cursor = null`. The wire's
 * own supersession note states a superseded batch is STILL SERVED; no other
 * byte changes.
 *
 * W-HR-A added the `next_cursor` delta: the map's full-book walk now runs on
 * mount and follows cursors to exhaustion, and this mock answers EVERY request
 * with the same body. A non-null cursor over a constant response is an endless
 * walk in the fixture, not in the product — terminating the page is what makes
 * the mock a book rather than a loop.
 */
const POSITIONS_AAVE_SUPERSEDED = {
  ...POSITIONS_AAVE_PAGE_1,
  next_cursor: null,
  batch: {
    ...POSITIONS_AAVE_PAGE_1.batch,
    supersession: { ...POSITIONS_AAVE_PAGE_1.batch.supersession, superseded: true },
  },
};

/**
 * DERIVED FIXTURE (provenance): the landed `positions-aave-page-1.json` with
 * `next_cursor = null` (so the walk terminates against a constant mock) and
 * every row's `total_debt` set to `"0"`. A borrower with nothing outstanding is
 * an ordinary book row, and its debt cell is a COMPUTED zero — the thing the
 * Book's fetch-failure strip used to claim did not exist on the page.
 */
const POSITIONS_COMPUTED_ZERO_DEBT = {
  ...POSITIONS_AAVE_PAGE_1,
  next_cursor: null,
  positions: POSITIONS_AAVE_PAGE_1.positions.map((position) => ({
    ...position,
    total_debt: "0",
  })),
};

/** An SSE `unavailable` frame carrying the server's OWN staleness statement. */
const SSE_UNAVAILABLE_FRAME =
  `event: unavailable\ndata: ${JSON.stringify({
    batch: null,
    reason: "no complete risk batch is available",
    stale_since_seconds: 42,
    last_good_batch_id: 1,
  })}\n\n`;

const SSE_SNAPSHOT_FRAME = `event: snapshot\ndata: ${JSON.stringify(FEED_POSTURE_SNAPSHOT)}\n\n`;

const SSE_RECOVERED_FRAME = `event: snapshot\ndata: ${JSON.stringify({
  ...FEED_POSTURE_SNAPSHOT,
  recovered: true,
})}\n\n`;

/** No horizontal document overflow at a mobile breakpoint (±2px rounding). */
async function expectNoHorizontalOverflow(page: Page): Promise<void> {
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(2);
}

// ---------------------------------------------------------------------------
// The matrix. One row per (surface × state) cell.
// ---------------------------------------------------------------------------

interface Cell {
  surface: string;
  state: string;
  path: string;
  /** Mobile cells set a viewport BEFORE navigation. */
  viewport?: { width: number; height: number };
  mock: (page: Page) => Promise<void>;
  /** Optional interaction between navigation and verification. */
  act?: (page: Page) => Promise<void>;
  verify: (page: Page) => Promise<void>;
}

const MATRIX: Cell[] = [
  // ---- Book -----------------------------------------------------------
  {
    surface: "book",
    state: "loading",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", stall);
      await page.route("**/v1/positions*", stall);
    },
    verify: async (page) => {
      await expect(page.getByTestId("book-loading")).toBeVisible();
      await expect(page.getByText("loading the first page…")).toBeVisible();
      // Nothing pending is ever rendered as a zero.
      await expect(page.locator("body")).not.toContainText("$0");
    },
  },
  {
    surface: "book",
    state: "ok",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await mockBookOk(page);
    },
    verify: async (page) => {
      await expect(page.getByTestId("book-stats-aave_v3_etherfi")).toContainText("8,000");
      // Engines never blend: no cross-engine sum in any unit.
      await expect(page.locator("body")).not.toContainText("12,200");
      // Every chart states its as-of: the risk map declares its own batch.
      // W-HR-A: the map walks the whole book by itself, so its as-of rides the
      // completed-walk head rather than a partial-view label.
      await expect(page.getByTestId("risk-map-full-head")).toContainText("as-of batch #1");
      // Severity is color AND form: the wad panel's eligible buckets carry
      // the filled-square form cue (2 sub-1.00 buckets in the fixture).
      await expect(page.getByTestId("hist-eligible-mark")).toHaveCount(2);
    },
  },
  {
    surface: "book",
    state: "refused:engine-withheld",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, BOOK_ENGINE_REFUSED));
      await page.route("**/v1/positions*", (route) => fulfillJson(route, POSITIONS_AAVE_PAGE_1));
    },
    verify: async (page) => {
      // The withheld engine is visible, named, and its null totals are em
      // dashes — never zeros.
      await expect(page.getByTestId("book-refused-engines")).toContainText("aave_v3_etherfi");
      const badDebt = page.getByTestId("bad-debt-aave_v3_etherfi");
      await expect(badDebt).toContainText("—");
      await expect(badDebt).not.toContainText("$0");
      await expect(page.getByTestId("book-stats-aave_v3_etherfi")).toContainText(
        "withheld, no number served",
      );
    },
  },
  {
    surface: "book",
    state: "error:503-no-batch",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, BOOK_ERROR_UNAVAILABLE, 503));
      await page.route("**/v1/positions*", (route) =>
        fulfillJson(route, BOOK_ERROR_UNAVAILABLE, 503),
      );
    },
    verify: async (page) => {
      await expect(page.getByTestId("book-no-batch")).toContainText("NO SERVABLE BATCH");
      await expect(page.getByTestId("book-no-batch")).toContainText("statement about the SERVICE");
      // Scoped to the aggregates this block stands in for: the positions table
      // walks its own endpoint and may serve a computed zero below.
      await expect(page.getByTestId("book-no-batch")).toContainText(
        "unavailable aggregate values are not rendered as zero",
      );
      // The positions table refuses in the refusal register (W-UX-B): the
      // server's sentence verbatim, its own retry named, NO retry button.
      const refusal = page.getByTestId("positions-refusal");
      await expect(refusal).toContainText("REFUSED · unavailable");
      await expect(refusal).toContainText("retry after 5s");
      await expect(refusal.getByRole("button")).toHaveCount(0);
      // No aggregate zeroes appear anywhere on the degraded surface.
      await expect(page.getByTestId("book-stats-aave_v3_etherfi")).toHaveCount(0);
    },
  },
  {
    surface: "book",
    state: "error:429",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429));
      await page.route("**/v1/positions*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
    },
    verify: async (page) => {
      const strip = page.getByRole("alert").filter({ hasText: "BOOK FETCH FAILED" });
      await expect(strip).toContainText("rate limit");
      // The claim is SCOPED to what this strip lost. The positions table walks
      // its own endpoint and may render a computed zero below, so a page-wide
      // "nothing here is rendered as zero" was an over-claim.
      await expect(strip).toContainText(
        "The aggregates are unavailable. Unavailable aggregate values are not rendered as zero.",
      );
      await expect(strip).not.toContainText("nothing here is rendered as zero");
      await expect(page.getByTestId("book-stats-aave_v3_etherfi")).toHaveCount(0);
    },
  },
  {
    surface: "book",
    state: "error:500",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, FEED_ERROR_INTERNAL, 500));
      await page.route("**/v1/positions*", (route) => fulfillJson(route, FEED_ERROR_INTERNAL, 500));
    },
    verify: async (page) => {
      const strip = page.getByRole("alert").filter({ hasText: "BOOK FETCH FAILED" });
      await expect(strip).toContainText("failed to build the response");
      // The claim is SCOPED to what this strip lost. The positions table walks
      // its own endpoint and may render a computed zero below, so a page-wide
      // "nothing here is rendered as zero" was an over-claim.
      await expect(strip).toContainText(
        "The aggregates are unavailable. Unavailable aggregate values are not rendered as zero.",
      );
      await expect(strip).not.toContainText("nothing here is rendered as zero");
    },
  },
  {
    // W-CH-B finding 6 — THE SCOPE OF A REFUSAL CLAIM.
    //
    // The strip used to say "nothing here is rendered as zero", which is a
    // claim about the whole page. The positions table walks its OWN endpoint
    // and keeps serving while /v1/book is down, so a row with no borrowings
    // legitimately renders a COMPUTED ZERO directly beneath the strip. An
    // over-claimed refusal costs the same trust a hidden one does: the reader
    // sees the register contradicted and stops reading it.
    surface: "book",
    state: "error:500-book-with-positions-computed-zero",
    path: "/book?engine=aave_v3_etherfi&dust=off",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, FEED_ERROR_INTERNAL, 500));
      await page.route("**/v1/positions*", (route) =>
        fulfillJson(route, POSITIONS_COMPUTED_ZERO_DEBT),
      );
    },
    verify: async (page) => {
      const strip = page.getByRole("alert").filter({ hasText: "BOOK FETCH FAILED" });
      await expect(strip).toContainText("failed to build the response");
      // SCOPED to what this strip lost.
      await expect(strip).toContainText(
        "The aggregates are unavailable. Unavailable aggregate values are not rendered as zero.",
      );
      await expect(strip).not.toContainText("nothing here is rendered as zero");
      // No aggregate rendered a zero: the stat rows are absent entirely.
      await expect(page.getByTestId("book-stats-aave_v3_etherfi")).toHaveCount(0);

      // …and the positions table BELOW it renders a real computed zero, which
      // is exactly why the old sentence was false.
      const table = page.getByRole("table", { name: "positions for aave_v3_etherfi" });
      await expect(table).toBeVisible();
      // `textContent`, not `innerText`: the header register is uppercased by
      // CSS, and `innerText` returns what the transform painted.
      const headers = await table
        .locator("thead th")
        .evaluateAll((nodes) => nodes.map((node) => node.textContent ?? ""));
      const debtColumn = headers.findIndex((header) => header.includes("Debt"));
      expect(debtColumn).toBeGreaterThan(-1);
      const debtCell = table
        .locator("tbody tr:not([data-testid='window-spacer'])")
        .first()
        .locator("td")
        .nth(debtColumn);
      // A COMPUTED ZERO, printed as a number. Not an em dash, which is what an
      // unknowable prints, and which the strip's claim is actually about.
      await expect(debtCell).toHaveText("0");
      await expect(debtCell).not.toHaveText("—");
    },
  },
  {
    surface: "book",
    state: "degraded:batch-superseded-409",
    // W-HR-A moved the default engine to debt_manager; this case is written
    // against the aave pages, so it names its engine.
    path: "/book?engine=aave_v3_etherfi",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, BOOK));
      let cursorRequests = 0;
      await page.route("**/v1/positions*", (route) => {
        const url = new URL(route.request().url());
        // The map's hoisted full-book walk shares this endpoint and sends no
        // `sort`; only the TABLE's continuation carries the 409 under test.
        const isTable = url.searchParams.get("sort") !== null;
        if (url.searchParams.get("cursor") === null)
          return fulfillJson(route, POSITIONS_AAVE_PAGE_1);
        if (!isTable) return fulfillJson(route, POSITIONS_AAVE_PAGE_2);
        // First cursor presentation answers 409; the restarted walk's cursor
        // is honored (the W-UX-C sentinel drives both without a click).
        cursorRequests += 1;
        if (cursorRequests === 1) return fulfillJson(route, BATCH_SUPERSEDED, 409);
        return fulfillJson(route, POSITIONS_AAVE_PAGE_2);
      });
    },
    act: async (page) => {
      await expect(
        page.getByRole("table", { name: "positions for aave_v3_etherfi" }),
      ).toContainText("0xAAaA…0001");
    },
    verify: async (page) => {
      const notice = page.getByTestId("batch-superseded-notice");
      await expect(notice).toContainText("BATCH SUPERSEDED");
      await expect(notice).toContainText("restarted from page one");
    },
  },
  {
    surface: "book",
    state: "refused:never-swept-collateral",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await mockBookOk(page);
    },
    act: async (page) => {
      await page.getByRole("button", { name: "debt_manager" }).click();
    },
    verify: async (page) => {
      const table = page.getByRole("table", { name: "positions for debt_manager" });
      // The never-swept account is a visible refused ROW with its named
      // reason and an ABSENT sweep mark — counted, never dropped.
      await expect(table).toContainText("REFUSED · SWEEP_NEVER");
      await expect(table).toContainText("S ∅");
      const refusedRow = table.getByRole("row").filter({ hasText: "0xddDD…0004" });
      await expect(refusedRow).toContainText("—");
      await expect(refusedRow).not.toContainText("$0");
      // The refused row is COUNTED in the W-UX-C accounting: it qualifies
      // under the dust step (refused rows are never dust) and stays in every
      // denominator.
      await expect(page.getByTestId("positions-accounting")).toHaveText(
        "2 loaded of 2 qualifying (dust <$1) · 0 hidden below step · 2 on book · sort headroom ▲",
      );
    },
  },
  {
    surface: "book",
    state: "degraded:superseded-still-served",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/book", (route) => fulfillJson(route, BOOK));
      await page.route("**/v1/positions*", (route) =>
        fulfillJson(route, POSITIONS_AAVE_SUPERSEDED),
      );
    },
    verify: async (page) => {
      // The supersession flag is the CONTRACT: still served, visibly so —
      // in the table foot AND on the chart's own as-of.
      await expect(page.getByText("SUPERSEDED (still served)").first()).toBeVisible();
      await expect(page.getByTestId("risk-map-full-head")).toContainText(
        "SUPERSEDED (still served)",
      );
    },
  },
  {
    surface: "book",
    state: "responsive:mobile",
    path: "/book",
    viewport: { width: 390, height: 844 },
    mock: async (page) => {
      await muteStream(page);
      await mockBookOk(page);
    },
    verify: async (page) => {
      await expect(page.getByRole("heading", { level: 1, name: "Book" })).toBeVisible();
      await expect(page.getByTestId("book-stats-aave_v3_etherfi")).toBeVisible();
      await expectNoHorizontalOverflow(page);
    },
  },

  // ---- Inspector ------------------------------------------------------
  {
    surface: "inspector",
    state: "loading",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/params*", stall);
      await page.route("**/v1/events*", stall);
      await page.route("**/v1/address/*/history*", stall);
      await page.route("**/v1/address/*", stall);
    },
    verify: async (page) => {
      await expect(page.getByText("querying the newest servable batch…")).toBeVisible();
      await expect(page.getByText("loading history…")).toBeVisible();
      await expect(page.getByTestId("found-positive")).toHaveCount(0);
    },
  },
  {
    surface: "inspector",
    state: "ok:found-with-stale-price",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_FOUND);
    },
    verify: async (page) => {
      await expect(page.getByTestId("found-positive")).toBeVisible();
      // No fake freshness: the stale verdict is its OWN visible state,
      // alongside the fresh one — never silently normalized.
      await expect(page.getByTestId("price-verdict").filter({ hasText: "stale" })).toBeVisible();
      await expect(page.getByTestId("price-verdict").filter({ hasText: "fresh" })).toBeVisible();
    },
  },
  {
    surface: "inspector",
    state: "empty:not-found-definitive",
    path: `/inspector/${NOT_FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_NOT_FOUND);
    },
    verify: async (page) => {
      // The ONE state entitled to say "no position": a definitive negative
      // from a complete lookup — empty, but PROVEN empty.
      await expect(page.getByTestId("found-negative")).toBeVisible();
      await expect(page.getByTestId("found-negative")).toContainText("no position");
      await expect(page.getByTestId("found-unknowable")).toHaveCount(0);
    },
  },
  {
    surface: "inspector",
    state: "refused:found-null-unknowable",
    path: `/inspector/${UNKNOWABLE_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_UNKNOWABLE);
    },
    verify: async (page) => {
      // found:null NEVER renders "no position" — asserted structurally: the
      // definitive-negative panel must be ABSENT and the unknowable panel
      // present with its phrase and the withheld engine NAMED.
      await expect(page.getByTestId("found-unknowable")).toBeVisible();
      await expect(page.getByTestId("found-unknowable")).toContainText("cannot be established");
      await expect(page.getByTestId("found-unknowable")).toContainText("debt_manager");
      await expect(page.getByTestId("found-negative")).toHaveCount(0);
    },
  },
  {
    surface: "inspector",
    state: "ok:history-gaps-hoverable",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_FOUND);
    },
    verify: async (page) => {
      const history = page.getByTestId("hf-history");
      // The refused batch is a GAP tick (never a value)…
      await expect(history.getByTestId("sparkline-gap")).toHaveCount(1);
      // …and the FINITE point carries an invisible hover target too
      // (SHOULD-FIX 8): values are as reachable as refusal reasons.
      await expect(history.getByTestId("sparkline-hit")).toHaveCount(1);
      await expect(history).toContainText("never interpolates");
    },
  },
  {
    surface: "inspector",
    state: "error:429",
    path: `/inspector/${FOUND_ADDR}`,
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/params*", (route) => fulfillJson(route, PARAMS));
      await page.route("**/v1/events*", (route) => fulfillJson(route, EVENTS));
      await page.route("**/v1/address/*/history*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
      await page.route("**/v1/address/*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
    },
    verify: async (page) => {
      // An error is NOT an answer: neither "no position" nor a position.
      await expect(page.getByText("lookup unavailable")).toBeVisible();
      await expect(page.getByText("an error is not an answer", { exact: false })).toBeVisible();
      await expect(page.getByText("rate limited (429)", { exact: false }).first()).toBeVisible();
      await expect(page.getByTestId("found-negative")).toHaveCount(0);
    },
  },
  {
    surface: "inspector",
    state: "responsive:mobile",
    path: `/inspector/${FOUND_ADDR}`,
    viewport: { width: 390, height: 844 },
    mock: async (page) => {
      await muteStream(page);
      await mockInspector(page, ADDRESS_FOUND);
    },
    verify: async (page) => {
      await expect(page.getByTestId("found-positive")).toBeVisible();
      await expectNoHorizontalOverflow(page);
    },
  },

  // ---- Scenario Lab ---------------------------------------------------
  {
    surface: "lab",
    state: "ok",
    path: "/lab",
    mock: async (page) => {
      await muteStream(page);
      await mockLabCold(page);
      await mockStress(page, STRESS_AAVE.address, labFixture("stress-aave.json"));
    },
    act: async (page) => {
      await runStress(page, STRESS_AAVE.address);
    },
    verify: async (page) => {
      await expect(page.getByTestId("lab-found")).toBeVisible();
      // Chips come from the WIRE's committed set, never a hardcoded list.
      await expect(page.getByTestId("lab-chip")).toHaveCount(STRESS_AAVE.scenarios.length);
    },
  },
  {
    surface: "lab",
    state: "refused:found-null-unknowable",
    path: "/lab",
    mock: async (page) => {
      await muteStream(page);
      await mockLabCold(page);
      await mockStress(page, STRESS_UNKNOWABLE.address, labFixture("stress-unknowable.json"));
    },
    act: async (page) => {
      await runStress(page, STRESS_UNKNOWABLE.address);
    },
    verify: async (page) => {
      await expect(page.getByText("cannot be established").first()).toBeVisible();
      // Structural (the wire note QUOTES the phrase while negating it): the
      // definitive-negative panel is absent.
      await expect(page.getByTestId("lab-not-found")).toHaveCount(0);
    },
  },
  {
    surface: "lab",
    state: "error:429",
    path: "/lab",
    mock: async (page) => {
      await muteStream(page);
      await mockLabCold(page);
      await mockStress(
        page,
        STRESS_AAVE.address,
        JSON.stringify(FEED_ERROR_RATE_LIMITED),
        429,
      );
    },
    act: async (page) => {
      await runStress(page, STRESS_AAVE.address);
    },
    verify: async (page) => {
      await expect(page.getByTestId("lab-error")).toContainText("rate limited (429)");
    },
  },
  {
    surface: "lab",
    state: "degraded:run-book-not-served-404",
    path: "/lab",
    mock: async (page) => {
      await muteStream(page);
      await mockLabCold(page);
      await page.route(`${API}/v1/scenarios/*/run-book`, (route) =>
        route.fulfill({
          status: 404,
          contentType: "application/json",
          headers: CORS,
          body: labFixture("error-not-found.json"),
        }),
      );
    },
    // W-SD-A CHANGED THIS CASE: reaching the run control no longer requires an
    // address lookup first. Book mode is the default and learns the committed
    // set from `GET /v1/scenarios`, so the 404 state is one click from arrival.
    act: async (page) => {
      await page.getByTestId("run-book-button").click();
    },
    verify: async (page) => {
      // The honest 404: named state, no spinner, no fake data.
      await expect(page.getByTestId("runbook-not-served")).toContainText(
        "book-wide stress not yet served by this deployment",
      );
      await expect(page.getByTestId("book-result")).toHaveCount(0);
    },
  },

  // ---- Observatory ----------------------------------------------------
  {
    surface: "observatory",
    state: "loading",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/observatory/series*", stall);
    },
    verify: async (page) => {
      await expect(page.getByTestId("observatory-loading")).toBeVisible();
    },
  },
  {
    surface: "observatory",
    state: "ok:absent-bucket",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await mockObservatory(page);
    },
    verify: async (page) => {
      // The chart states its as-of (the newest bucket's own watermark)…
      await expect(page.getByTestId("observatory-newest")).toContainText("watermark block");
      // …and an ABSENT bucket is a NAMED gap on the axis, never interpolated.
      // (toBeAttached: a stroke-only SVG tick has a zero-width box, which
      // Playwright's visibility heuristic reports as hidden.)
      await expect(
        page.getByTestId("observatory-chart-debt_usd").locator('[data-kind="absent"]').first(),
      ).toBeAttached();
    },
  },
  {
    surface: "observatory",
    state: "refused:withheld-bucket",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await mockObservatory(page);
    },
    act: async (page) => {
      await page.getByTestId("observatory-engine-debt_manager").click();
    },
    verify: async (page) => {
      // Severity = color AND form: the withheld gap wears the outlined
      // warn square, not just a hue.
      await expect(page.getByTestId("obs-gap-warn").first()).toBeVisible();
      await expect(
        page.getByTestId("observatory-chart-debt_usd").locator('[data-kind="withheld"]').first(),
      ).toBeAttached();
      await expect(page.locator("body")).not.toContainText("$0");
    },
  },
  {
    surface: "observatory",
    state: "degraded:rollup-unavailable",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/observatory/series*", (route) =>
        fulfillJson(route, OBSERVATORY_DEGRADED, 503),
      );
    },
    verify: async (page) => {
      const degraded = page.getByTestId("observatory-degraded");
      await expect(degraded).toContainText("a named state rather than an empty chart");
      // Never an empty chart, never zeros.
      await expect(page.getByTestId("observatory-chart-debt_usd")).toHaveCount(0);
    },
  },
  {
    surface: "observatory",
    state: "error:500",
    path: "/observatory",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/observatory/series*", (route) =>
        fulfillJson(route, FEED_ERROR_INTERNAL, 500),
      );
    },
    verify: async (page) => {
      const strip = page.getByRole("alert").filter({ hasText: "SERIES FETCH FAILED" });
      await expect(strip).toContainText("unavailable, and none of it is being shown as empty");
    },
  },

  // ---- Feed -----------------------------------------------------------
  {
    surface: "feed",
    state: "ok:untimed-tail-disclosed",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_CROSS_PAGE_1));
    },
    verify: async (page) => {
      await expect(page.getByTestId("feed-row")).toHaveCount(2);
      // No fake freshness: the untimed row renders its BLOCK, never an
      // invented timestamp, and the tail boundary is DISCLOSED.
      await expect(page.getByTestId("untimed-divider")).toHaveCount(1);
      await expect(page.getByTestId("feed-time").nth(1)).toHaveText("block 154,796,490");
    },
  },
  {
    surface: "feed",
    state: "empty:filter-matches-nothing",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_EMPTY));
    },
    verify: async (page) => {
      const empty = page.getByTestId("feed-empty");
      await expect(empty).toContainText("no custodied chain actions match this filter");
      await expect(empty).toContainText("a real answer");
      await expect(page.getByTestId("feed-row")).toHaveCount(0);
    },
  },
  {
    surface: "feed",
    state: "refused:bad-cursor-400",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => {
        const url = new URL(route.request().url());
        if (url.searchParams.get("cursor") === null)
          return fulfillJson(route, FEED_CROSS_PAGE_1);
        return fulfillJson(route, FEED_ERROR_BAD_CURSOR, 400);
      });
    },
    act: async (page) => {
      await expect(page.getByTestId("feed-row")).toHaveCount(2);
      await page.getByTestId("feed-load-more").click();
    },
    verify: async (page) => {
      // The refusal renders the envelope's own words; loaded rows survive.
      await expect(page.getByTestId("feed-refusal")).toBeVisible();
      await expect(page.getByTestId("feed-restart")).toBeVisible();
      await expect(page.getByTestId("feed-row")).toHaveCount(2);
    },
  },
  {
    surface: "feed",
    state: "error:429",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) =>
        fulfillJson(route, FEED_ERROR_RATE_LIMITED, 429),
      );
    },
    verify: async (page) => {
      await expect(page.getByTestId("feed-error")).toContainText("rate limit");
    },
  },
  {
    surface: "feed",
    state: "error:500",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_ERROR_INTERNAL, 500));
    },
    verify: async (page) => {
      await expect(page.getByTestId("feed-error")).toContainText("failed to build the response");
    },
  },
  {
    surface: "feed",
    state: "live:no-base-frame",
    path: "/feed",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_CROSS_PAGE_1));
    },
    verify: async (page) => {
      // Nothing is pretended: no snapshot means no batch strip at all.
      await expect(page.getByTestId("feed-live-none")).toContainText("nothing is pretended");
      await expect(page.getByTestId("feed-live-batch")).toHaveCount(0);
    },
  },
  {
    surface: "feed",
    state: "live:snapshot-never-history",
    path: "/feed",
    mock: async (page) => {
      await mockStreamBody(page, SSE_SNAPSHOT_FRAME);
      await page.route("**/v1/events*", (route) => fulfillJson(route, FEED_CROSS_PAGE_1));
    },
    verify: async (page) => {
      // Live posture renders the batch's REAL watermark vector…
      await expect(page.getByTestId("feed-live-batch")).toContainText("batch #1");
      await expect(page.getByTestId("feed-live-batch")).toContainText("@25,635,618");
      // …and stays labeled live-only: posture is never conflated with history.
      await expect(page.getByTestId("feed-live-strip")).toContainText("current connection only");
    },
  },

  // ---- Proof Center ---------------------------------------------------
  {
    surface: "proof",
    state: "ok:proof-and-live-split",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_MANIFEST));
    },
    verify: async (page) => {
      // Two subjects; the reconciled-exact claim lives ONLY on the proof
      // card — a live batch never reads as reconciled-exact.
      await expect(page.getByTestId("proof-subject")).toContainText("PROOF · EXACT");
      await expect(page.getByTestId("live-subject")).not.toContainText("PROOF · EXACT");
    },
  },
  {
    surface: "proof",
    state: "refused:receipt-rejected",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_PROOF_FAILED));
    },
    verify: async (page) => {
      await expect(page.getByTestId("proof-status")).toContainText("RECEIPT REJECTED");
      // The live subject keeps ITS truth — serving continues, unconflated.
      await expect(page.getByTestId("live-status")).toContainText("SERVING");
      await expect(page.locator("body")).not.toContainText("PROOF · EXACT @");
    },
  },
  {
    surface: "proof",
    state: "empty:no-committed-receipt",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_NO_RECEIPT));
    },
    verify: async (page) => {
      await expect(page.getByTestId("proof-status")).toContainText("NO COMMITTED RECEIPT");
      await expect(page.getByTestId("live-status")).toContainText("SERVING");
    },
  },
  {
    surface: "proof",
    state: "error:no-servable-batch",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => fulfillJson(route, EVIDENCE_NO_BATCH));
    },
    verify: async (page) => {
      await expect(page.getByTestId("live-status")).toContainText("NO SERVABLE BATCH");
      // No key is ever fabricated for a batch that does not exist.
      await expect(page.getByTestId("materialization-key")).toContainText("never fabricated");
    },
  },
  {
    surface: "proof",
    state: "error:evidence-unreachable",
    path: "/proof",
    mock: async (page) => {
      await muteStream(page);
      await page.route("**/v1/evidence*", (route) => route.abort());
    },
    verify: async (page) => {
      await expect(page.getByTestId("proof-unavailable")).toBeVisible();
      // Neither subject is invented while the manifest is unreachable.
      await expect(page.getByTestId("proof-subject")).toHaveCount(0);
      await expect(page.getByTestId("live-subject")).toHaveCount(0);
    },
  },

  // ---- Developers -----------------------------------------------------
  {
    surface: "developers",
    state: "ok",
    path: "/developers",
    mock: async (page) => {
      await muteStream(page);
    },
    verify: async (page) => {
      // Generated verbatim from the contract; the error vocabulary renders
      // including the 409 supersession envelope.
      await expect(page.getByTestId("endpoint-getEvidence")).toBeVisible();
      await expect(page.getByTestId("error-BatchSuperseded")).toBeVisible();
    },
  },

  // ---- Shell / global posture ribbon ----------------------------------
  {
    surface: "shell",
    state: "live:sse-down",
    path: "/book",
    mock: async (page) => {
      await muteStream(page);
      await mockBookOk(page);
    },
    verify: async (page) => {
      // With no stream the header states the STREAM's truth — never a fake
      // LIVE chip (the vector-only Ribbon makes that unrepresentable).
      const header = page.getByRole("banner");
      await expect(
        header.getByText(/STREAM · (CONNECTING|RECONNECTING|AWAITING BASE|CLOSED)/),
      ).toBeVisible();
      await expect(header.getByText("LIVE · WATERMARKED")).toHaveCount(0);
    },
  },
  {
    surface: "shell",
    state: "live:sse-snapshot",
    path: "/book",
    mock: async (page) => {
      await mockStreamBody(page, SSE_SNAPSHOT_FRAME);
      await mockBookOk(page);
    },
    verify: async (page) => {
      const header = page.getByRole("banner");
      // The ribbon's payload is the REAL watermark vector, never one number.
      await expect(header.getByText("@25,635,618")).toBeVisible();
      // WAVE R7 (round-15 finding 4). `mockStreamBody` fulfils a COMPLETE
      // response, which ends the stream the instant the snapshot lands — the
      // client raises "the server closed the stream" and spends its life on the
      // reconnect backoff. This cell used to assert `LIVE · WATERMARKED` over
      // that, because holding a batch was the entire qualification for the
      // green chip. It is not any more: LIVE is a claim about the CURRENT
      // connection (open, base delivered), and this mock cannot give one. The
      // SNAPSHOT'S DATA — what this cell is actually about — is untouched and
      // asserted above; the badge states the connection honestly.
      //
      // LIVE over a genuinely held-open stream is pinned in r7-fixes.spec.ts,
      // against a real SSE server that does not hang up.
      await expect(
        header.getByText(/STREAM · (CONNECTING|RECONNECTING|AWAITING BASE|CLOSED)/),
      ).toBeVisible();
      await expect(header.getByText("LIVE · WATERMARKED")).toHaveCount(0);
    },
  },
  {
    surface: "shell",
    state: "live:sse-unavailable-stale-last-good",
    path: "/book",
    mock: async (page) => {
      await mockStreamBody(page, SSE_UNAVAILABLE_FRAME);
      await mockBookOk(page);
    },
    verify: async (page) => {
      // The server's OWN staleness statement renders — the UI invents none.
      const header = page.getByRole("banner");
      await expect(header.getByText("NO SERVABLE BATCH")).toBeVisible();
      await expect(header.getByText(/stale/)).toBeVisible();
      await expect(header.getByText("42s")).toBeVisible();
    },
  },
  {
    surface: "shell",
    state: "live:sse-recovered",
    path: "/book",
    mock: async (page) => {
      // Unavailable, then the recovery snapshot — one connection's frames.
      await mockStreamBody(page, `${SSE_UNAVAILABLE_FRAME}${SSE_RECOVERED_FRAME}`);
      await mockBookOk(page);
    },
    verify: async (page) => {
      // Recovery renders the batch again: the real vector, and NO RESIDUE of
      // the unavailable state — which is what this cell is for.
      //
      // WAVE R7: the badge no longer says LIVE, for the same reason as the
      // sse-snapshot cell above — `mockStreamBody` ends the body, so there is
      // no open connection to be live on. The recovery itself is unaffected:
      // the batch is back, the staleness statement is gone.
      const header = page.getByRole("banner");
      await expect(header.getByText("@25,635,618")).toBeVisible();
      await expect(header.getByText("NO SERVABLE BATCH")).toHaveCount(0);
      await expect(header.getByText("LIVE · WATERMARKED")).toHaveCount(0);
    },
  },
];

// ---------------------------------------------------------------------------
// The driver: one test per cell.
// ---------------------------------------------------------------------------

for (const cell of MATRIX) {
  test(`${cell.surface} × ${cell.state}`, async ({ page }) => {
    if (cell.viewport !== undefined) await page.setViewportSize(cell.viewport);
    await cell.mock(page);
    await page.goto(cell.path);
    if (cell.act !== undefined) await cell.act(page);
    await cell.verify(page);
  });
}
